<?php

namespace cymapgt\core\utility\logger;

use Monolog\Logger as MonologLogger;
use FemtoPixel\Monolog\Handler\CsvHandler;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-21 at 23:39:38.
 */
class LoggerTest extends \PHPUnit\Framework\TestCase {

   /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() : void {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() : void {
        
    }
    
    /**
     * Test the addHandler function by passing in configurations for a CSV handler7
     * 
     * @covers cymapgt\core\utility\logger\Logger::addLogHandler
     */
    public function testAddLogHandler() {
        //create random string, which we will as CSV File name
        $randomName = $this->generateRandomName();
        $randomNameFq = "files/$randomName.csv";
        
        //prepare configurations for the log handler
        $logHandlerConfig = array (
            $randomNameFq,
            MonologLogger::WARNING
        );
        
        //bootstrap the log handler
        $logHandlerBootstrap = array (
            '\FemtoPixel\Monolog\Handler\CsvHandler' => array (
                'handler_parameters' => $logHandlerConfig
            )
        );
        
        //assert the random file doesnt exist
        $this->assertFileNotExists($randomNameFq);
        
        //instantiate cymapgt logger and process log
        $cgtLogger = new Logger('femtopixel_csv_test');
        $cgtLogger->addLogHandler($logHandlerBootstrap, true);
        $concreteLogger = $cgtLogger->getLoggerNew();
        
        //write the log
        $logMessage = "Sissoko for Balon d\'Or 2019";
        $concreteLogger->addWarning (
            $logMessage
        );
        
        //assert the file exists
        $this->assertFileExists($randomNameFq);
        
        //open file and assert first line is as logged
        $logFileInMemory = file($randomNameFq);
        $this->assertStringStartsWith("'Sissoko for Balon d\'Or 2019'", $logFileInMemory[0]);
        
        //destroy the testfile
        unlink($randomNameFq);
    }
    
    /**
     * Test Logging with a pre-configured Logger injected to the LoggerAwareInterface
     * 
     */
    public function testSetLogger() {
        //create random string, which we will as CSV File name
        $randomName = $this->generateRandomName();
        $randomNameFq = "files/$randomName.csv";
        
        // create a log channel
        $log = new MonologLogger('name');
        $log->pushHandler(new CsvHandler($randomNameFq, MonologLogger::WARNING));
        
        //our log message
        $logMessage = 'Foo';

        //assert the random file doesnt exist
        $this->assertFileNotExists($randomNameFq);
        
        //Set and get the logger (developer scenario)
        $cgtLogger = new Logger('femtopixel_csv_test');
        $cgtLogger->setLogger($log);
        $log2 = $cgtLogger->getLoggerNew();
        
        
        // add records to the log
        $log2->addWarning($logMessage);
        
        //assert the file exists
        $this->assertFileExists($randomNameFq);
        
        //open file and assert first line is as logged
        $logFileInMemory = file($randomNameFq);
        $this->assertStringStartsWith('Foo', $logFileInMemory[0]);
        
        //destroy the test file
        unlink($randomNameFq);
    }
    
    /**
     * Helper function to generate random 4 digit string
     * 
     * @return string
     */
    protected function generateRandomName() {
        $randomBytes = \openssl_random_pseudo_bytes(2);
        $randomName = bin2hex($randomBytes);
        return $randomName;
    }
}
